version: "3.9"

services:

  portfolio:
    image: ghcr.io/cyborg-s/portfolio
    restart: unless-stopped

  pokedex:
    image: ghcr.io/cyborg-s/pokedex
    restart: unless-stopped

  sharky:
    image: ghcr.io/cyborg-s/sharky
    restart: unless-stopped

  join:
    image: ghcr.io/cyborg-s/join
    restart: unless-stopped