name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Node.js (für Angular)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4️⃣ Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: cyborg-s
          password: ${{ secrets.GHCR_PAT }}

      # ---------------- Angular Build ----------------
      - name: Build portfolio Angular app
        working-directory: portfolio/public
        run: |
          npm ci
          npx ng build --configuration production

      # ---------------- Build & Push Docker Images ----------------
      - name: Build and push Docker images
        run: |
          # Portfolio
          docker build -t ghcr.io/${{ github.actor }}/portfolio:latest ./portfolio
          docker push ghcr.io/${{ github.actor }}/portfolio:latest

          # Pokedex
          docker build -t ghcr.io/${{ github.actor }}/pokedex:latest ./pokedex
          docker push ghcr.io/${{ github.actor }}/pokedex:latest

          # Sharky
          docker build -t ghcr.io/${{ github.actor }}/sharky:latest ./sharky
          docker push ghcr.io/${{ github.actor }}/sharky:latest

          # Join
          docker build -t ghcr.io/${{ github.actor }}/join:latest ./join
          docker push ghcr.io/${{ github.actor }}/join:latest

          # Proxy
          docker build -t ghcr.io/${{ github.actor }}/proxy:latest ./proxy
          docker push ghcr.io/${{ github.actor }}/proxy:latest

          # Contact API
          docker build -t ghcr.io/${{ github.actor }}/contact-api:latest ./contact-api
          docker push ghcr.io/${{ github.actor }}/contact-api:latest
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            cd /home/factaccttig/opt/webapp
            docker compose pull
            docker compose up -d