name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ---------------- Login GHCR ----------------
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------------- Portfolio (Angular) ----------------
      - name: Build portfolio Angular app
        working-directory: portfolio/public
        run: |
          npm ci
          npx ng build --configuration production

      - name: Build & Push Docker images
        run: |
          # Portfolio
          docker build -t ghcr.io/cyborg-s/portfolio:latest ./portfolio
          docker push ghcr.io/cyborg-s/portfolio:latest

          # Pokedex
          docker build -t ghcr.io/cyborg-s/pokedex:latest ./pokedex
          docker push ghcr.io/cyborg-s/pokedex:latest

          # Sharky
          docker build -t ghcr.io/cyborg-s/sharky:latest ./sharky
          docker push ghcr.io/cyborg-s/sharky:latest

          # Join
          docker build -t ghcr.io/cyborg-s/join:latest ./join
          docker push ghcr.io/cyborg-s/join:latest

          # Contact API
          docker build -t ghcr.io/cyborg-s/contact-api:latest ./contact-api
          docker push ghcr.io/cyborg-s/contact-api:latest

          # Proxy
          docker build -t ghcr.io/cyborg-s/proxy:latest ./proxy
          docker push ghcr.io/cyborg-s/proxy:latest